spring:
  datasource:
    druid:
      # 数据库访问配置, 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/douglee?useUnicode=true&characterEncoding=utf8
      username: root
      password: root
  thymeleaf:
    cache: false
    mode: LEGACYHTML5

mybatis:
  config-location: classpath:config/mybatis-config.xml
  type-aliases-package: com.example.springbootshiro.domain
  mapper-locations: classpath:mapper/*.xml
  property:
    order: BEFORE

#mappers 多个接口时逗号隔开
mapper:
  mappers: com.example.springbootshiro.config.MyMapper
  not-empty: false
  identity: MYSQL
  order: after

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
