spring:
  datasource:
    url: jdbc:mysql://localhost:3306/douglee
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.DefaultComponentSafeNamingStrategy
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect
mybatis:
  config-location: classpath:config/mybatis-config.xml
  type-aliases-package: com.example.springbootshiro.domain
  mapper-locations: classpath:mapper/*.xml
  property:
    order: BEFORE

