spring:
  datasource:
    mysql:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://192.168.103.237/test
      username: cnki
      password: cnki

      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
    mssql:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
      jdbc-url: jdbc:mysql://192.168.103.237/test
      username: sa
      password: cnki1234!

      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
  jpa:
    show-sql: true
